# Generated by Django 5.1 on 2025-04-05 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=150, unique=True)),
                ('receiver_img', models.ImageField(blank=True, default='profile_pict.png', upload_to='receiver_pictures')),
                ('receiver_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('dark_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.BooleanField(default=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('chat_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsettings')),
            ],
        ),
    ]
